<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Condition=" '$(VisualStudioVersion)' == '17.0' ">
    <TargetFrameworks>net20;net46;net5.0-windows;net6.0-windows;netcoreapp2.1;netcoreapp3.1</TargetFrameworks>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(VisualStudioVersion)' != '17.0' ">
    <TargetFrameworks>net20;net40;net46;netcoreapp2.1</TargetFrameworks>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace>WebPWrapperLib</RootNamespace>
    <AssemblyName>WebPWrapperLib</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <NoWarn>NETSDK1138;NU1902;NU1903</NoWarn>
	<DebugType>portable</DebugType>
	<GenerateDocumentationFile>True</GenerateDocumentationFile>
	<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	<Title>WebP Wrapper</Title>
	<Authors>Repzilon</Authors>
	<Company>(none)</Company>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<RepositoryType>git</RepositoryType>
	<PackageTags>webp</PackageTags>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<PackageIcon>webplogo.png</PackageIcon>
	<PackageProjectUrl>https://github.com/repzilon/WebP-wrapper-animatedWebP/tree/repzilon</PackageProjectUrl>
	<RepositoryUrl>https://github.com/repzilon/WebP-wrapper-animatedWebP.git</RepositoryUrl>
	<Description>The most complete wrapper for libwebp in C# with animated WebP support.</Description>
	<Copyright>© 2012-2019 Jose M. Piñeiro, © 2021, 2025 Repzilon, © 2022 thomas694, © 2023 russaa</Copyright>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="x64\libsharpyuv.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="x64\libwebp.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="x64\libwebpdecoder.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="x64\libwebpdemux.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="x86\libsharpyuv.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="x86\libwebp.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="x86\libwebpdecoder.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="x86\libwebpdemux.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp2.1'">
    <PackageReference Include="System.Drawing.Common" Version="[5.0.3]" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp3.1'">
    <PackageReference Include="System.Drawing.Common" Version="[6.0.0]" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net5.0-windows'">
    <PackageReference Include="System.Drawing.Common" Version="[6.0.0]" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0-windows'">
    <PackageReference Include="System.Drawing.Common" Version="[8.0.17]" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\webplogo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>