<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Condition=" '$(VisualStudioVersion)' == '17.0' ">
    <TargetFrameworks>net46;net5.0-windows;net6.0-windows;netcoreapp3.1</TargetFrameworks>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(VisualStudioVersion)' != '17.0' ">
    <TargetFrameworks>net20;net40;net46</TargetFrameworks>
  </PropertyGroup>
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <DebugType>portable</DebugType>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>WebPTest</RootNamespace>
    <AssemblyName>WebPTest</AssemblyName>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <NoWarn>NETSDK1138</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net20'">
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="WebPExample.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="WebPExample.Designer.cs">
      <DependentUpon>WebPExample.cs</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Content Include="WildCherry.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="YellowRose.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="WebPWrapper.cs" />
    <Compile Remove="Properties\Resources.Designer.cs" />
    <Compile Remove="Properties\Settings.Designer.cs" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Remove="WebPExample.resx" />
  </ItemGroup>
  <ItemGroup>
    <None Include="WebPExample.resx">
      <DependentUpon>WebPExample.cs</DependentUpon>
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WebPWrapperLib\WebPWrapperLib-Sdk.csproj" />
  </ItemGroup>
  <ItemGroup Condition=" '$(VisualStudioVersion)' != '17.0' ">
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
</Project>